# Generated by Django 3.1.7 on 2021-03-04 21:57

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=10)),
                ('apellido', models.CharField(max_length=15)),
                ('mensaje', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Posteo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=10)),
                ('apellido', models.CharField(max_length=15)),
                ('titulo', models.CharField(max_length=20)),
                ('comentario', models.CharField(max_length=50)),
                ('imagen', models.ImageField(upload_to='photos')),
            ],
            managers=[
                ('objeto_panel', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('contrasenia', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=10)),
                ('apellido', models.CharField(max_length=15)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=15)),
                ('provincia', models.CharField(max_length=15)),
            ],
        ),
    ]
