# Generated by Django 3.1.7 on 2021-03-13 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.TextField(default='', max_length=150, verbose_name='Comentario')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(default='', max_length=50, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('asunto', models.CharField(default='', max_length=50, verbose_name='Asunto')),
                ('mensaje', models.TextField(default='', max_length=500, verbose_name='Mensaje')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(default='', max_length=20, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, default='', max_length=100, null=True, verbose_name='Descripción')),
                ('imagen', models.ImageField(upload_to='media/posteos')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('like', models.IntegerField(default=0)),
                ('cantidad_comentarios', models.IntegerField(default=0)),
                ('autor', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tublogApp.comentario')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posteos',
            },
        ),
    ]
