# Generated by Django 3.1.7 on 2021-03-06 23:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tublogApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posteo',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='posteo',
            name='comentario',
        ),
        migrations.RemoveField(
            model_name='posteo',
            name='nombre',
        ),
        migrations.AddField(
            model_name='posteo',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='posteo',
            name='fecha_publicacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tublogApp.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='posteo',
            name='id_comentario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tublogApp.comentario'),
        ),
    ]
