# Generated by Django 3.1.7 on 2021-03-14 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tublogApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cantidad_comentarios',
        ),
        migrations.RemoveField(
            model_name='post',
            name='id_comentario',
        ),
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
    ]
