# Generated by Django 3.1.7 on 2021-03-07 01:01

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('tublogApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='contacto',
            managers=[
                ('objeto_panel', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='contacto',
            name='mensaje',
            field=models.TextField(blank=True),
        ),
    ]
