# Generated by Django 3.1.7 on 2021-03-14 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tublogApp', '0003_auto_20210314_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='descripcion',
            field=models.TextField(blank=True, default='', max_length=300, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(default='', max_length=50, verbose_name='Título'),
        ),
    ]
