# Generated by Django 3.1.7 on 2021-03-14 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tublogApp', '0004_auto_20210314_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(upload_to='media/posteos'),
        ),
    ]
