# Generated by Django 3.1.7 on 2021-03-12 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tublogApp', '0007_auto_20210311_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='comentario',
            new_name='id_comentario',
        ),
    ]
