# Generated by Django 3.1.7 on 2021-03-12 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tublogApp', '0008_auto_20210311_2152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AlterField(
            model_name='comentario',
            name='comentario',
            field=models.TextField(default='', max_length=150, verbose_name='Comentario'),
        ),
    ]
