# Generated by Django 3.1.7 on 2021-03-12 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tublogApp', '0009_auto_20210311_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='comentario',
            new_name='contenido',
        ),
    ]
