# Generated by Django 3.1.7 on 2021-03-12 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tublogApp', '0010_auto_20210311_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='contenido',
            field=models.TextField(max_length=150, verbose_name='Comentario'),
        ),
    ]
